{% set version='2.5.3' %}

package:
  name: kissplice
  version: {{ version }}

source:
  url: "ftp://pbil.univ-lyon1.fr/pub/logiciel/kissplice/download/kissplice-{{ version }}.tar.gz"
  sha256: "98c28b602414b6a20c20d481159837c2462d66adc87b74d055916e90de7187b5"

build:
  number: 0
  skip: True  # [py2k]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - zlib
    - python
  run:
    - python

test:
  commands:
    - kissplice -h

about:
  home: http://kissplice.prabi.fr
  license: CeCILL license
  summary: A local transcriptome assembler for SNPs, indels and AS events
